### ISSUE TITLE
_sort not working

### ISSUE THREAD

**Issue by devilbags** [RTICWDT/open-data-maker#37] opened 2017-11-26 20:04 UTC
Trying to do a sorted search just like the example. The server will return `500: Internal server error` whenever I try to append a sort field.
Try the url for example: [Sample URL request](https://api.data.gov/ed/collegescorecard/v1/schools.json?&school.degrees_awarded.predominant=3,4&school.state=MA&_sort=population&api_key=your_api_key). P.S. Replace api key with your key

Without the `_sort`, everything works fine

**Comment by kynetiv** [comment] 2017-11-27 14:10
Hi @devilbags, I believe the issue is that `population` is not a field in the dataset and the `_sort` parameter is causing an internal error instead of a more helpful error message. If you haven't already looked at the [data dictionary](https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx) you can see the `dev-category` and `developer-friendly name` parameters and their descriptions of what is available in the dataset. 

If you were looking to sort by enrollment numbers you might try this query using the `2015.student.size` variable: https://api.data.gov/ed/collegescorecard/v1/schools.json?&fields=id,school.name,school.degrees_awarded.predominant,2015.student.size&school.degrees_awarded.predominant=3,4&school.state=MA&_sort=2015.student.size&api_key=your_api_key

(I added a `fields` parameter to limit the results in this example)

**Comment by devilbags** [comment] 2017-11-27 15:06
@kynetiv Thanks for answering. The`_sort` example in the API introduction should include this correct example.

**Comment by kynetiv** [comment] 2018-02-26 21:29
Closing but feel free to reopen if you think there's still an issue here.

**Closed by kynetiv** 2018-02-26 21:29 UTC
